name: Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manual run ke liye

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyTelegramBotAPI requests

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          NSFWROUTER_API_KEY: ${{ secrets.NSFWROUTER_API_KEY }}
        run: |
          python bot.py
